CREATE DATABASE USER_SERVICE;
USE USER_SERVICE;

-- si ya esta creada la base de datos
DROP TABLE USUARIO;
-- fin drop

CREATE TABLE USUARIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(100),
    APELLIDOS VARCHAR(100),
    ADMINISTRADOR BOOLEAN,
	EMAIL VARCHAR(50),
    PASS  VARCHAR(20)
);

SELECT * from USUARIO;