version: '3.8'
services: 
    db:
        build: 
            context: ./db-jwt
            dockerfile: Dockerfile
        container_name: mysql-container-jwt
        ports:
            - "3306:3306"
        volumes:
            - ./bd/data:/var/lib/mysql
    web:
        build:
            context: ./JWT
            dockerfile: Dockerfile
        container_name: jwt-service
        ports:
            - "3000:3000"
        links: 
            - "db:db"
        depends_on: 
            - db
        environment: 
            - DATABASE_HOST=db
    