CREATE DATABASE BDTORNEOS;

USE BDTORNEOS;

CREATE TABLE JUEGOS(
ID INTEGER NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50),
IP VARCHAR(20),
PRIMARY KEY(ID)
);

CREATE TABLE TORNEOS(
ID INTEGER NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50),
FECHA DATE,
PRIMARY KEY(ID)
);

CREATE TABLE PARTIDAS(
ID INTEGER NOT NULL AUTO_INCREMENT,
UUID VARCHAR(50), 
JUGADOR1 VARCHAR(20),
JUGADOR2 VARCHAR(20),
IP_JUEGO VARCHAR(20),
ESTADO VARCHAR(2),
ID_TORNEO INTEGER NOT NULL,
FECHA_CREACION DATE,
FECHA_JUGADO DATE,
PRIMARY KEY(ID),
FOREIGN KEY (ID_TORNEO) REFERENCES TORNEOS(ID)
);

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'admin';

SELECT * FROM bdtorneos.JUEGOS;
SELECT COUNT(*) FROM JUEGOS;
SELECT ID FROM JUEGOS WHERE NOMBRE = "PIRATAS";

INSERT INTO JUEGOS(NOMBRE, IP) VALUES("PIRATAS DEL CARIBE", "192.168.1.1");
