version: '3.8'
services: 
    db:
        build: 
            context: ./db_juegos
            dockerfile: Dockerfile
        container_name: mysql-container-juegos
        ports:
            - "3306:3306"
        volumes:
            - ./bd/data:/var/lib/mysql
    web:
        build:
            context: ./Juegos
            dockerfile: Dockerfile
        container_name: juegos-service
        ports:
            - "3005:3005"
        links: 
            - "db:db"
        depends_on: 
            - db
        environment: 
            - DATABASE_HOST=db
    