version: '3.1'
services: 
    api:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: service-dados
        restart: always
        env_file: 
            - ./.env
        ports: 
            - "3000:3000"